// <auto-generated />
using MVCBD.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MVCBD.Migrations
{
    [DbContext(typeof(RolContext))]
    [Migration("20191022051729_rroles")]
    partial class rroles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MVCBD.Db.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NombreRol");

                    b.HasKey("IdRol");

                    b.ToTable("roles");
                });
#pragma warning restore 612, 618
        }
    }
}
